pub const STATIC_SEARCH_RESIDUAL_BUCKET_COUNT: usize = 6;
pub const STATIC_SEARCH_RESIDUAL_BUCKET_NAMES = [_][]const u8{ "0_15", "16_31", "32_63", "64_127", "128_255", "256p" };
pub const StaticSearchResidualCounters = [STATIC_SEARCH_RESIDUAL_BUCKET_COUNT]u64;

pub const MoveOrderBucket = enum(usize) {
    tt,
    promotion,
    good_capture,
    bad_capture,
    killer_a,
    killer_b,
    countermove,
    positive_history_quiet,
    zero_history_quiet,
    negative_history_quiet,
    other,
};

pub const MOVE_ORDER_BUCKET_NAMES = [_][]const u8{
    "tt",
    "promotion",
    "good_capture",
    "bad_capture",
    "killer_a",
    "killer_b",
    "countermove",
    "positive_history_quiet",
    "zero_history_quiet",
    "negative_history_quiet",
    "other",
};
pub const MOVE_ORDER_BUCKET_COUNT: usize = MOVE_ORDER_BUCKET_NAMES.len;
pub const MoveOrderCounters = [MOVE_ORDER_BUCKET_COUNT]u64;

pub const MOVE_ORDER_DEPTH_BAND_NAMES = [_][]const u8{ "d1", "d2_3", "d4_5", "d6_8", "d9p" };
pub const MOVE_ORDER_DEPTH_BAND_COUNT: usize = MOVE_ORDER_DEPTH_BAND_NAMES.len;
pub const MOVE_ORDER_NODE_TYPE_NAMES = [_][]const u8{ "pv", "cut", "all" };
pub const MOVE_ORDER_NODE_TYPE_COUNT: usize = MOVE_ORDER_NODE_TYPE_NAMES.len;
pub const MoveOrderDetailCounters = [MOVE_ORDER_NODE_TYPE_COUNT][MOVE_ORDER_DEPTH_BAND_COUNT][MOVE_ORDER_BUCKET_COUNT]u64;
pub const MoveOrderDetailScoreSums = [MOVE_ORDER_NODE_TYPE_COUNT][MOVE_ORDER_DEPTH_BAND_COUNT][MOVE_ORDER_BUCKET_COUNT]i64;

pub const MoveOrderSample = struct {
    bucket: MoveOrderBucket,
    node_type: usize,
    depth_band: usize,
    history_score: i32,
};

pub fn moveOrderDepthBand(depth: u16) usize {
    if (depth <= 1) return 0;
    if (depth <= 3) return 1;
    if (depth <= 5) return 2;
    if (depth <= 8) return 3;
    return 4;
}

pub fn moveOrderNodeType(pv_node: bool, cut_node: bool) usize {
    if (pv_node) return 0;
    if (cut_node) return 1;
    return 2;
}

pub const zero_move_order_detail_counters: MoveOrderDetailCounters = [_][MOVE_ORDER_DEPTH_BAND_COUNT][MOVE_ORDER_BUCKET_COUNT]u64{
    [_][MOVE_ORDER_BUCKET_COUNT]u64{[_]u64{0} ** MOVE_ORDER_BUCKET_COUNT} ** MOVE_ORDER_DEPTH_BAND_COUNT,
} ** MOVE_ORDER_NODE_TYPE_COUNT;

pub const zero_move_order_detail_score_sums: MoveOrderDetailScoreSums = [_][MOVE_ORDER_DEPTH_BAND_COUNT][MOVE_ORDER_BUCKET_COUNT]i64{
    [_][MOVE_ORDER_BUCKET_COUNT]i64{[_]i64{0} ** MOVE_ORDER_BUCKET_COUNT} ** MOVE_ORDER_DEPTH_BAND_COUNT,
} ** MOVE_ORDER_NODE_TYPE_COUNT;

pub const SearchStats = struct {
    qnodes: u64 = 0,
    main_static_evals: u64 = 0,
    reverse_futility_prunes: u64 = 0,
    reverse_futility_prunes_depth_1: u64 = 0,
    reverse_futility_prunes_depth_2: u64 = 0,
    reverse_futility_prunes_depth_3: u64 = 0,
    iir_reductions: u64 = 0,
    iir_pv_reductions: u64 = 0,
    iir_cut_reductions: u64 = 0,
    iir_all_reductions: u64 = 0,
    check_extensions: u64 = 0,
    rfp_hint_probes: u64 = 0,
    rfp_hint_cutoffs: u64 = 0,
    rfp_hint_cutoffs_depth_1: u64 = 0,
    rfp_hint_cutoffs_depth_2: u64 = 0,
    rfp_hint_cutoffs_depth_3: u64 = 0,
    rfp_hint_alpha_raises: u64 = 0,
    // Raw-eval cache. Probes happen ONLY after a TT static-eval
    // miss, so hits/probes IS the hit-after-TT-miss rate.
    eval_cache_probes: u64 = 0,
    eval_cache_hits: u64 = 0,
    eval_cache_q_probes: u64 = 0,
    eval_cache_q_hits: u64 = 0,
    quiet_futility_prunes: u64 = 0,
    late_move_prunes: u64 = 0,
    bad_capture_prunes: u64 = 0,
    tt_probes: u64 = 0,
    tt_hits: u64 = 0,
    tt_hit_current_generation: u64 = 0,
    tt_hit_old_generation: u64 = 0,
    tt_hit_age_1: u64 = 0,
    tt_hit_age_2_3: u64 = 0,
    tt_hit_age_4p: u64 = 0,
    tt_hit_with_move: u64 = 0,
    tt_hit_without_move: u64 = 0,
    tt_hit_exact_bound: u64 = 0,
    tt_hit_lower_bound: u64 = 0,
    tt_hit_upper_bound: u64 = 0,
    tt_shallow_hits: u64 = 0,
    tt_ordering_only_hits: u64 = 0,
    tt_ordering_only_current_generation: u64 = 0,
    tt_ordering_only_old_generation: u64 = 0,
    tt_bound_no_cutoff_hits: u64 = 0,
    tt_cutoffs: u64 = 0,
    tt_cutoffs_current_generation: u64 = 0,
    tt_cutoffs_old_generation: u64 = 0,
    tt_stores: u64 = 0,
    tt_store_skipped_same_generation_deeper: u64 = 0,
    tt_store_skip_new_with_move: u64 = 0,
    tt_store_skip_new_without_move: u64 = 0,
    tt_store_skip_victim_with_move: u64 = 0,
    tt_store_skip_victim_without_move: u64 = 0,
    tt_store_empty: u64 = 0,
    tt_store_same_key: u64 = 0,
    tt_store_replacements: u64 = 0,
    tt_store_replaced_current_generation: u64 = 0,
    tt_store_replaced_old_generation: u64 = 0,
    tt_store_replaced_with_move: u64 = 0,
    tt_store_replaced_without_move: u64 = 0,
    tt_store_replaced_exact_bound: u64 = 0,
    tt_store_replaced_lower_bound: u64 = 0,
    tt_store_replaced_upper_bound: u64 = 0,
    tt_store_new_with_move: u64 = 0,
    tt_store_new_without_move: u64 = 0,
    tt_store_new_exact_bound: u64 = 0,
    tt_store_new_lower_bound: u64 = 0,
    tt_store_new_upper_bound: u64 = 0,
    tt_exact_cutoffs: u64 = 0,
    tt_lower_cutoffs: u64 = 0,
    tt_upper_cutoffs: u64 = 0,
    beta_cutoffs: u64 = 0,
    beta_cutoffs_first: u64 = 0,
    main_capture_cutoffs: u64 = 0,
    main_capture_cutoffs_first: u64 = 0,
    main_capture_cutoffs_1_2: u64 = 0,
    main_capture_cutoffs_3_5: u64 = 0,
    main_capture_cutoffs_6p: u64 = 0,
    main_good_capture_cutoffs: u64 = 0,
    main_bad_capture_cutoffs: u64 = 0,
    main_quiet_cutoffs: u64 = 0,
    main_quiet_cutoffs_first: u64 = 0,
    main_quiet_cutoffs_1_2: u64 = 0,
    main_quiet_cutoffs_3_5: u64 = 0,
    main_quiet_cutoffs_6p: u64 = 0,
    main_quiet_tt_cutoffs: u64 = 0,
    main_quiet_killer_a_cutoffs: u64 = 0,
    main_quiet_killer_b_cutoffs: u64 = 0,
    main_quiet_countermove_cutoffs: u64 = 0,
    countermove_table_probes: u64 = 0,
    countermove_table_misses: u64 = 0,
    countermove_table_hits: u64 = 0,
    countermove_table_legal_hits: u64 = 0,
    countermove_table_stale_hits: u64 = 0,
    main_quiet_positive_history_cutoffs: u64 = 0,
    main_quiet_nonpositive_history_cutoffs: u64 = 0,
    qsearch_capture_cutoffs: u64 = 0,
    qsearch_capture_cutoffs_first: u64 = 0,
    qsearch_capture_cutoffs_1_2: u64 = 0,
    qsearch_capture_cutoffs_3_5: u64 = 0,
    qsearch_capture_cutoffs_6p: u64 = 0,
    qsearch_good_capture_cutoffs: u64 = 0,
    qsearch_bad_capture_cutoffs: u64 = 0,
    null_tries: u64 = 0,
    null_cutoffs: u64 = 0,
    null_verify_rejects: u64 = 0,
    hard_stops_external: u64 = 0,
    hard_stops_node_limit: u64 = 0,
    hard_stops_maximum_budget: u64 = 0,
    lmr_reductions: u64 = 0,
    lmr_total_reduction: u64 = 0,
    lmr_pv_reductions: u64 = 0,
    lmr_nonpv_reductions: u64 = 0,
    lmr_cut_reductions: u64 = 0,
    lmr_all_reductions: u64 = 0,
    lmr_cut_reductions_3_5: u64 = 0,
    lmr_cut_reductions_6_7: u64 = 0,
    lmr_cut_reductions_8p: u64 = 0,
    lmr_deep_reductions: u64 = 0,
    lmr_cut_deep_reductions: u64 = 0,
    lmr_all_deep_reductions: u64 = 0,
    lmr_researches: u64 = 0,
    lmr_pv_researches: u64 = 0,
    lmr_nonpv_researches: u64 = 0,
    lmr_cut_researches: u64 = 0,
    lmr_all_researches: u64 = 0,
    lmr_cut_researches_3_5: u64 = 0,
    lmr_cut_researches_6_7: u64 = 0,
    lmr_cut_researches_8p: u64 = 0,
    lmr_deep_researches: u64 = 0,
    lmr_cut_deep_researches: u64 = 0,
    lmr_all_deep_researches: u64 = 0,
    lmr_cut_deep_researches_3_5: u64 = 0,
    lmr_cut_deep_researches_6_7: u64 = 0,
    lmr_cut_deep_researches_8p: u64 = 0,
    lmr_all_deep_researches_3_5: u64 = 0,
    lmr_all_deep_researches_6_7: u64 = 0,
    lmr_all_deep_researches_8p: u64 = 0,
    lmr_cut_deep_research_margin_0_31: u64 = 0,
    lmr_cut_deep_research_margin_32_95: u64 = 0,
    lmr_cut_deep_research_margin_96p: u64 = 0,
    lmr_all_deep_research_margin_0_31: u64 = 0,
    lmr_all_deep_research_margin_32_95: u64 = 0,
    lmr_all_deep_research_margin_96p: u64 = 0,
    lmr_cut_deep_research_nonpositive_history: u64 = 0,
    lmr_cut_deep_research_positive_history: u64 = 0,
    lmr_all_deep_research_nonpositive_history: u64 = 0,
    lmr_all_deep_research_positive_history: u64 = 0,
    lmr_verification_fail_lows: u64 = 0,
    lmr_verification_alpha_raises: u64 = 0,
    lmr_verification_cutoffs: u64 = 0,
    lmr_deep_verification_fail_lows: u64 = 0,
    lmr_deep_verification_alpha_raises: u64 = 0,
    lmr_deep_verification_cutoffs: u64 = 0,
    lmr_cut_verification_alpha_raises: u64 = 0,
    lmr_cut_deep_verification_fail_lows: u64 = 0,
    lmr_cut_deep_verification_alpha_raises: u64 = 0,
    lmr_cut_deep_verification_cutoffs: u64 = 0,
    lmr_cut_deep_verification_fail_lows_3_5: u64 = 0,
    lmr_cut_deep_verification_fail_lows_6_7: u64 = 0,
    lmr_cut_deep_verification_fail_lows_8p: u64 = 0,
    lmr_cut_deep_verification_cutoffs_3_5: u64 = 0,
    lmr_cut_deep_verification_cutoffs_6_7: u64 = 0,
    lmr_cut_deep_verification_cutoffs_8p: u64 = 0,
    lmr_all_deep_verification_fail_lows_3_5: u64 = 0,
    lmr_all_deep_verification_fail_lows_6_7: u64 = 0,
    lmr_all_deep_verification_fail_lows_8p: u64 = 0,
    lmr_all_deep_verification_cutoffs_3_5: u64 = 0,
    lmr_all_deep_verification_cutoffs_6_7: u64 = 0,
    lmr_all_deep_verification_cutoffs_8p: u64 = 0,
    lmr_cut_deep_verification_fail_lows_nonpositive_history: u64 = 0,
    lmr_cut_deep_verification_fail_lows_positive_history: u64 = 0,
    lmr_cut_deep_verification_cutoffs_nonpositive_history: u64 = 0,
    lmr_cut_deep_verification_cutoffs_positive_history: u64 = 0,
    lmr_all_deep_verification_fail_lows_nonpositive_history: u64 = 0,
    lmr_all_deep_verification_fail_lows_positive_history: u64 = 0,
    lmr_all_deep_verification_cutoffs_nonpositive_history: u64 = 0,
    lmr_all_deep_verification_cutoffs_positive_history: u64 = 0,
    lmr_cut_verification_fail_lows_3_5: u64 = 0,
    lmr_cut_verification_fail_lows_6_7: u64 = 0,
    lmr_cut_verification_fail_lows_8p: u64 = 0,
    lmr_cut_verification_cutoffs_3_5: u64 = 0,
    lmr_cut_verification_cutoffs_6_7: u64 = 0,
    lmr_cut_verification_cutoffs_8p: u64 = 0,
    lmr_cut_cutoffs: u64 = 0,
    lmr_cut_cutoffs_3_5: u64 = 0,
    lmr_cut_cutoffs_6_7: u64 = 0,
    lmr_cut_cutoffs_8p: u64 = 0,
    singular_candidates: u64 = 0,
    singular_cut_candidates: u64 = 0,
    singular_candidates_6_7: u64 = 0,
    singular_candidates_8p: u64 = 0,
    singular_weak_alternative_candidates: u64 = 0,
    singular_verifications: u64 = 0,
    singular_verified: u64 = 0,
    singular_extensions: u64 = 0,
    pvs_scouts: u64 = 0,
    pvs_researches: u64 = 0,
    aspiration_researches: u64 = 0,
    aspiration_fail_lows: u64 = 0,
    aspiration_fail_highs: u64 = 0,
    qsearch_stand_pat_cutoffs: u64 = 0,
    staged_main_movegen_nodes: u64 = 0,
    staged_main_legal_moves: u64 = 0,
    staged_main_quiet_moves: u64 = 0,
    staged_main_tactical_moves: u64 = 0,
    staged_main_tt_legal_nodes: u64 = 0,
    staged_main_nodes_with_quiets: u64 = 0,
    staged_main_no_quiet_searched_nodes: u64 = 0,
    staged_main_no_quiet_searched_quiet_moves: u64 = 0,
    qsearch_tactical_nodes: u64 = 0,
    qsearch_tactical_moves: u64 = 0,
    qsearch_bad_capture_skips: u64 = 0,
    static_search_residual_nodes: StaticSearchResidualCounters = [_]u64{0} ** STATIC_SEARCH_RESIDUAL_BUCKET_COUNT,
    static_search_residual_exact: StaticSearchResidualCounters = [_]u64{0} ** STATIC_SEARCH_RESIDUAL_BUCKET_COUNT,
    static_search_residual_lower: StaticSearchResidualCounters = [_]u64{0} ** STATIC_SEARCH_RESIDUAL_BUCKET_COUNT,
    static_search_residual_upper: StaticSearchResidualCounters = [_]u64{0} ** STATIC_SEARCH_RESIDUAL_BUCKET_COUNT,
    static_search_residual_rfp: StaticSearchResidualCounters = [_]u64{0} ** STATIC_SEARCH_RESIDUAL_BUCKET_COUNT,
    static_search_residual_null: StaticSearchResidualCounters = [_]u64{0} ** STATIC_SEARCH_RESIDUAL_BUCKET_COUNT,
    static_search_residual_quiet_futility: StaticSearchResidualCounters = [_]u64{0} ** STATIC_SEARCH_RESIDUAL_BUCKET_COUNT,
    static_search_residual_late_move: StaticSearchResidualCounters = [_]u64{0} ** STATIC_SEARCH_RESIDUAL_BUCKET_COUNT,
    static_search_residual_bad_capture: StaticSearchResidualCounters = [_]u64{0} ** STATIC_SEARCH_RESIDUAL_BUCKET_COUNT,
    static_search_residual_lmr_research: StaticSearchResidualCounters = [_]u64{0} ** STATIC_SEARCH_RESIDUAL_BUCKET_COUNT,
    static_search_residual_lmr_verification_fail_low: StaticSearchResidualCounters = [_]u64{0} ** STATIC_SEARCH_RESIDUAL_BUCKET_COUNT,
    move_order_searched: MoveOrderCounters = [_]u64{0} ** MOVE_ORDER_BUCKET_COUNT,
    move_order_cutoffs: MoveOrderCounters = [_]u64{0} ** MOVE_ORDER_BUCKET_COUNT,
    move_order_first_cutoffs: MoveOrderCounters = [_]u64{0} ** MOVE_ORDER_BUCKET_COUNT,
    move_order_lmr_reductions: MoveOrderCounters = [_]u64{0} ** MOVE_ORDER_BUCKET_COUNT,
    move_order_lmr_researches: MoveOrderCounters = [_]u64{0} ** MOVE_ORDER_BUCKET_COUNT,
    move_order_lmr_fail_lows: MoveOrderCounters = [_]u64{0} ** MOVE_ORDER_BUCKET_COUNT,
    move_order_lmr_cutoffs: MoveOrderCounters = [_]u64{0} ** MOVE_ORDER_BUCKET_COUNT,
    move_order_detail_searched: MoveOrderDetailCounters = zero_move_order_detail_counters,
    move_order_detail_cutoffs: MoveOrderDetailCounters = zero_move_order_detail_counters,
    move_order_detail_first_cutoffs: MoveOrderDetailCounters = zero_move_order_detail_counters,
    move_order_detail_lmr_reductions: MoveOrderDetailCounters = zero_move_order_detail_counters,
    move_order_detail_lmr_researches: MoveOrderDetailCounters = zero_move_order_detail_counters,
    move_order_detail_lmr_fail_lows: MoveOrderDetailCounters = zero_move_order_detail_counters,
    move_order_detail_lmr_cutoffs: MoveOrderDetailCounters = zero_move_order_detail_counters,
    move_order_detail_history_score_sum: MoveOrderDetailScoreSums = zero_move_order_detail_score_sums,
    iteration_stop_maximum_elapsed: u64 = 0,
    iteration_stop_maximum_projected: u64 = 0,
    iteration_stop_optimum_elapsed: u64 = 0,
    iteration_stop_optimum_projected: u64 = 0,
};
